<?php

namespace CmsBundle\Entity\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all pages
     * 
     * @param type $order
     * @param type $readOnly
     * @return type
     */
    public function getPages()
    {
        $qb = $this->createQueryBuilder('page');
        
        return $qb->getQuery();
    }    
}