product:
    resource: ProductBundle\Controller\ProductController
    type:     rest
    prefix:   /api/product
    
page:
    resource: PageBundle\Controller\PageController
    type:     rest
    prefix:   /api/page

app:
    resource: AppBundle\Controller\AppController
    type:     rest
    prefix:   /api/app 
    
category:
    resource: ProductBundle\Controller\CategoryController
    type:     rest
    prefix:   /api/product-category