app:
    resource: "@AppBundle/Controller/AppController.php"
    type:     rest
    prefix:   /api/app
    
page:
    resource: "@PageBundle/Controller/PageController.php"
    type:     rest
    prefix:   /api/page