services:    
    app.service:
        class: AppBundle\Service\AppService
        public: false
        arguments: 
            - "@translator.default"
            - "@security.token_storage"
            - "@doctrine.orm.default_entity_manager"
            - "@request_stack"
            - "@knp_paginator"
            - "@validator"
            - "@app.session.service"
            - "%app_service_params%"
        
    app.md5encoder.service:
        class: AppBundle\Service\Md5Encoder
        arguments: 
            - "%app_saltmain%"
        
    app.session.service:
        class: AppBundle\Service\Session
        arguments: ~
        
    app.dataFixture.service:
        class: AppBundle\Service\DataFixture
        arguments:
            - "@app.service"