<?php

namespace ProductBundle\Entity\Repository;

use AppBundle\Library\Base\BaseEntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseEntityRepository
{   
    /**
     * Get all categories
     * 
     * @param type $loadProducts
     * @param type $order
     * @return type
     */
    public function getCategories($loadProducts = false, $order = 'c.id')
    {
        $qb = $this->getQueryBuilder()
            ->select('c.id, c.description, c.title') //gives control on how your api is shown to the client
            ->from('ProductBundle:Category', 'c')
            ->where('c.deleted = 0')
            ->orderBy($order);
        
        if ($loadProducts) {
            $qb->leftJoin('c.products', 'p', 'p.deleted = 0');
        }
        
        return $qb->getQuery()->getScalarResult();        
    }
    
    
    /**
     * 
     * @param int $categoryId
     * @return type
     */
    public function countCategoryProducts($categoryId)
    {
        $qb = $this->getQueryBuilder()
            ->select('count(p.id)')
            ->from('ProductBundle:Product', 'p')
            ->join('p.categories', 'c', 'WITH', 'c.id = :categoryId')
            ->where('p.deleted = 0')
            ->setParameter('categoryId', $categoryId);

        return intval($qb->getQuery()->getSingleScalarResult());
    }
    
    
    /**
     * Get one or null category
     * 
     * @param type $value
     * @param type $key
     * @return \ProductBundle\Entity\Category
     */
    public function getCategory($value, $key = 'id')
    {
        $qb = $this->getQueryBuilder()
            ->select('c')
            ->from('ProductBundle:Category', 'c')
            ->where(sprintf('c.%s = :%s AND c.deleted = 0', $key, $key))
            ->setParameter($key, $value);

        return $qb->getQuery()->getOneOrNullResult();
    }      
}