<?php

namespace ProductBundle\Entity\Repository;

use AppBundle\Library\Base\BaseEntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends BaseEntityRepository
{  
    /**
     * 
     * @return type
     */
    public function getAllOrders()
    {
        $qb = $this->getQueryBuilder()
            ->select('theOrder')
            ->from('ProductBundle:Order', 'theOrder');
        
        $orders = $qb->getQuery()->getResult();

        $orderData = array();
        foreach ($orders as $order) {
            $orderDetails = array();
            foreach ($order->getOrderDetail() as $orderDetail) {
                $orderDetails[] = array(
                    'product' => $orderDetail->getProduct()->getTitle(),
                    'count' => $orderDetail->getCount(),
                    'price' => $orderDetail->getPrice(),
                );
            }
            
            $orderData[] = array(
                'id' => $order->getId(),
                'name' => $order->getName(),
                'detail' => $orderDetails
            ); 
        }


//                . 'order.street, '
//                . 'order.city, '
//                . 'order.state, '
//                . 'order.zip, '
//                . 'order.country, '
//                . 'order.giftwrap '        
        
        return $orderData;
    }
}