<?php

namespace ProductBundle\Entity\Repository;

use AppBundle\Library\Base\BaseEntityRepository;

/**
 * OrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailRepository extends BaseEntityRepository
{  
}