<?php

namespace ProductBundle\Entity\Repository;

use AppBundle\Library\Base\BaseEntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends BaseEntityRepository
{  
    /**
     * 
     * @return type
     */
    public function getAllOrders($order = 'product.id')
    {
        $qb = $this->getQueryBuilder()
            ->select(''
                . 'order.id, '
                . 'order.name, '
                . 'order.street, '
                . 'order.city, '
                . 'order.state, '
                . 'order.zip, '
                . 'order.country, '
                . 'order.giftwrap '
                )
            ->from('ProductBundle:order', 'order')
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }
}